keys:
  - &users:
    - &giuseppe age1yy6ccf3hsx0wrmmaap0f66tmpyqfsuxrdtwxdvjzg2mmplnda3vqdrtpa7
  - &hosts:
    - &hana age1hc0u394vdc9natg4mmkf58nnevaxk8me247gtccg8hjehkcgupwsmmmsp7
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *giuseppe
          - *hana
